org.gradle.jvmargs=-Xmx4G -XX:+IgnoreUnrecognizedVMOptions -XX:+UseG1GC
org.gradle.parallel=true
org.gradle.caching=true

# Mod Properties
mod_id=mutilsc
mod_name=ModpackUtils Continued
mod_license=Apache-2.0
mod_authors=UltimatChamp & Welsey
mod_description=Various utilities for modpacks supported and updated for newer versions.
mod_version=1.2.0
maven_group=dev.ultimatchamp

# Providers
modrinthId=wklFEiuR
curseforgeId=1135297

# Minecraft Properties
loom.platform=[VERSIONED]
loom.ignoreDependencyLoomVersionValidation=true
deps.minecraft_version=[VERSIONED]
deps.quilt_mappings_build=[VERSIONED]
deps.mc_range=[VERSIONED]

# Fabric Properties - https://fabricmc.net/develop
deps.fabric_loader=[VERSIONED]
deps.fabric_api_version=[VERSIONED]

# (Neo)Forge Properties - https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=[VERSIONED]

# Dependencies
deps.yacl_version=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.mainmenucredits_version=[VERSIONED]

systemProp.fabric-loom.silent-access-widener-signatures=true
